import type { Metadata, Viewport } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { MessageBox, MessageBoxProvider } from "@/components/MessageBox";
import { SiteStructuredData } from "@/components/seo/StructuredData";
import { SITE_URL, SITE_NAME, SITE_LOCALE } from "@/lib/site";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
  // Accent face only; never in the first screen, so it must not compete with LCP.
  preload: false,
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const notoSansTCCritical = localFont({
  src: "./fonts/NotoSansTC-critical.woff2",
  variable: "--font-noto-sans-tc-critical",
  weight: "100 900",
  style: "normal",
  display: "swap",
  preload: true,
  fallback: ["PingFang TC", "Microsoft JhengHei", "Noto Sans CJK TC", "sans-serif"],
  adjustFontFallback: false,
});

// The full site subset stays available as a non-blocking fallback after the
// every-route first-screen subset has rendered. Its generated unicode-range is
// disjoint from critical, so a glyph is never matched against both faces.
const notoSansTC = localFont({
  src: "./fonts/NotoSansTC-subset.woff2",
  variable: "--font-noto-sans-tc",
  // 保留完整軸。實測限縮到 200–700 只省 8 KB，卻會讓日後用 font-black 直接壞掉。
  weight: "100 900",
  style: "normal",
  display: "swap",
  preload: false,
  // The subset covers every character on the site today. Anything added later
  // falls through to a real system Chinese face, never to a Latin default.
  fallback: ["PingFang TC", "Microsoft JhengHei", "Noto Sans CJK TC", "sans-serif"],
  // Important: Defaults to 'Arial' for next/font/local, which would apply Latin
  // metrics to Chinese text. Must be off.
  adjustFontFallback: false,
  // Generated by scripts/build-font-subset.py. Kept as a literal because
  // next/font evaluates this loader configuration at build time.
  declarations: [{ prop: "unicode-range", value: "U+0020-007E, U+00A9, U+00B0, U+00D7, U+00F7, U+03B2, U+2013, U+2018-2019, U+201C-201D, U+2026-2027, U+203B, U+2190-2191, U+2193, U+2198, U+2248, U+2264-2265, U+22EF, U+2460-2464, U+2500, U+25A0-25A1, U+25B2, U+25BC, U+25C6, U+25CB, U+25CF, U+2605-2606, U+2713, U+3000, U+3008-300B, U+300E-3011, U+3014-3015, U+4E01, U+4E16, U+4E1F, U+4E26, U+4E4E, U+4E82, U+4E8C, U+4E92, U+4EA4, U+4EAB, U+4EAE, U+4ECB, U+4ECD, U+4ED8-4ED9, U+4EE3, U+4EFB, U+4F0F, U+4F11, U+4F38, U+4F3C, U+4F4F-4F50, U+4F54-4F55, U+4F63, U+4F69, U+4F75, U+4F88, U+4F9B, U+4F9D, U+4FC2-4FC3, U+4FDD, U+4FEE, U+5009, U+500D, U+5012, U+5019, U+501F, U+5047, U+504F, U+5065, U+5099, U+50AC, U+50B3, U+50C5, U+50DA, U+50F9, U+5100, U+5132, U+5145, U+5149, U+514D, U+5152, U+5168, U+516B, U+516D, U+5171, U+5177, U+518A, U+51B0, U+51B7, U+51C6, U+5200, U+5207, U+5212, U+5217, U+521D, U+5236-5237, U+523B, U+5247, U+525B, U+5269, U+529F-52A0, U+52A3, U+52DE-52DF, U+52E2, U+52F5, U+52F8, U+5305, U+5319, U+532F, U+5339, U+5347-5348, U+5370, U+5377, U+537B, U+539A, U+539F, U+53C8, U+53CB, U+53CD, U+53D6-53D7, U+53E5, U+53EB, U+53F2-53F3, U+5404, U+5409, U+5411, U+541D, U+5426, U+542B, U+5433, U+5438, U+543B, U+5473, U+547C-547D, U+5496, U+54E5, U+54E9, U+54ED, U+5546, U+555F, U+5561, U+5584, U+559D, U+55C7, U+5617, U+5668, U+566A, U+5687, U+56B4, U+56F0, U+56FA, U+5708, U+570D, U+5713, U+5716, U+571F, U+573E, U+5740, U+5747, U+574A, U+5750-5751, U+576A, U+5783, U+578B, U+57AE, U+57CE, U+57DF, U+57F9, U+5805, U+584A, U+5851, U+5854, U+585E, U+586B, U+588A, U+58A8, U+58C7, U+58D3, U+58DE-58DF, U+591C, U+5920, U+5927, U+592A, U+592E, U+5931, U+5947, U+594F, U+5951, U+5957, U+5962, U+596E, U+5976, U+599D, U+59D3-59D4, U+5A01, U+5B50, U+5B57-5B58, U+5B63, U+5B78, U+5B83, U+5B85, U+5B88-5B89, U+5B98, U+5B9C, U+5BA3-5BA4, U+5BBF, U+5BC6, U+5BE7, U+5BE9, U+5BF8, U+5C07, U+5C0A-5C0B, U+5C0E, U+5C1A, U+5C24, U+5C2C, U+5C37, U+5C3A, U+5C3E, U+5C45, U+5C6C, U+5C71, U+5C94, U+5CB8, U+5CED, U+5D1B, U+5DBA, U+5DDE, U+5DE6, U+5DEE, U+5E03, U+5E2B, U+5E33, U+5E36, U+5E45, U+5E55, U+5E63, U+5E72-5E73, U+5E8F, U+5E97, U+5EA6-5EA7, U+5EAB, U+5EAD, U+5EE0, U+5EE3, U+5EF6, U+5EFA, U+5F04, U+5F15, U+5F31, U+5F35, U+5F37, U+5F48, U+5F62, U+5F71, U+5F80, U+5F85, U+5F91, U+5FAE, U+5FB5, U+5FB7, U+5FC3, U+5FD7-5FD8, U+5FEB, U+5FF5, U+5FFD, U+6015, U+601D, U+602A, U+6094, U+60B2, U+60C5, U+60E0, U+6101, U+611F, U+6123, U+614B, U+6158, U+6162-6163, U+6167, U+616E, U+6176, U+6191, U+61C9, U+6216, U+622A, U+6240, U+6253, U+625B, U+6263, U+626D, U+627F-6280, U+6284, U+6293, U+6295, U+6298, U+62B5, U+62BC-62BD, U+62C6, U+62CB, U+62CD, U+62D2, U+62D6, U+62DB, U+62EC, U+6301, U+6307, U+6311, U+6377, U+6388, U+6392, U+63A1, U+63A7, U+63AA, U+63CF-63D0, U+63F4, U+640D, U+6416, U+641C, U+642C-642D, U+6436, U+6469, U+6490, U+64A4-64A5, U+64AD, U+64C1, U+64C7, U+64CA-64CB, U+64CD-64CE, U+64D4, U+64DA, U+64E6, U+64EC, U+64F4, U+64FE, U+6524, U+652C, U+6539, U+653B, U+654F, U+6551, U+6557-6559, U+6562-6563, U+656C, U+6572, U+6599, U+65A5, U+65BD, U+65C1, U+65C5, U+65CF, U+65E2, U+65E5, U+65E9, U+660E, U+6620, U+666E-666F, U+667A, U+6696, U+66AB, U+66B4, U+66DD, U+66F2, U+66F8, U+66FE, U+670B, U+671B, U+672A-672B, U+6749, U+674E, U+6750, U+675F, U+676F, U+677F, U+6790, U+67D0, U+67D3, U+6821, U+6838, U+684C, U+68A8, U+68AF-68B0, U+68C4, U+6930, U+6975, U+6982, U+69CB, U+6A19, U+6A21, U+6A94, U+6AA2, U+6ABB, U+6B0A, U+6B3E, U+6B50, U+6B61-6B62, U+6B64-6B65, U+6B72, U+6B77-6B78, U+6B7B, U+6B8A, U+6BBA, U+6BBC, U+6BCD, U+6BDB, U+6C11, U+6C23, U+6C34, U+6C38, U+6C42, U+6C61, U+6C7D, U+6C83, U+6CB3, U+6CBB, U+6CC1, U+6CDB, U+6CF0, U+6D17, U+6D1B, U+6D32, U+6D3D-6D3E, U+6DB5, U+6DE8, U+6DF1, U+6DF7, U+6E1B, U+6E2F, U+6E38, U+6E96, U+6E9D, U+6EA2, U+6EAB, U+6ED1, U+6EEF, U+6EFE, U+6F02, U+6F0F, U+6F32, U+6F5B, U+6F62, U+6FC0, U+6FC3, U+6FFE, U+700F, U+7070, U+70B8, U+70C8, U+7121, U+7167, U+716E, U+71B1, U+71D2, U+7206, U+722D, U+7246-7248, U+7279, U+72AF, U+72C0, U+734E, U+7368, U+7372, U+73CD, U+73E0, U+73ED, U+7403, U+7463, U+74B0, U+74F6, U+751A, U+751C, U+751F, U+754C, U+7559, U+7565, U+7570, U+758A, U+767D, U+76AE, U+76BA, U+76CA, U+76DF, U+76E1, U+76E4, U+76EE, U+76F2, U+76F8, U+7761, U+77E9, U+77ED, U+780D, U+7814, U+7834, U+7838, U+786C, U+7891, U+78B0, U+78B3, U+78BC, U+78E8, U+78EF, U+790E, U+793A, U+793E, U+7968, U+7981, U+79C1, U+79D1-79D2, U+79DF, U+79FB, U+7A05, U+7A31, U+7A3D, U+7A4D, U+7A69, U+7A76, U+7A7A, U+7A81, U+7A84, U+7A97, U+7AE5, U+7AEF, U+7AF6, U+7B49, U+7BB1, U+7BC4, U+7BE9, U+7C21, U+7C3D, U+7C4C, U+7C97, U+7CB9, U+7CD6, U+7CD9, U+7CFB, U+7D04, U+7D14, U+7D1A, U+7D20-7D22, U+7D2F, U+7D39, U+7D42, U+7D71, U+7D81, U+7D9C, U+7DAD, U+7DB4, U+7DCA, U+7DD2, U+7DE8-7DE9, U+7DF4, U+7E2E, U+7E3E, U+7E41, U+7E54, U+7E6B, U+7E7C, U+7E8C, U+7F3A, U+7F44, U+7F6E, U+7F85, U+7F8A, U+7FA4, U+7FD2, U+7FFB, U+8001, U+8003, U+8058, U+805E, U+806F, U+8072, U+8077, U+807D, U+80A1, U+80B2, U+80CC, U+80E1, U+8108, U+8166, U+8170, U+81A0, U+81B3, U+81E8, U+81F3-81F4, U+81FA, U+8208-8209, U+820C, U+822A, U+822C, U+8259, U+826F, U+8272, U+828B, U+82B1, U+8305, U+8336, U+8349, U+83AB, U+83CC, U+83DC, U+83EF, U+8449, U+8457, U+8490, U+85A6, U+85AA, U+85CD, U+85DD, U+85E5, U+865B, U+865F, U+86CB, U+878D, U+8840, U+8853, U+8857, U+885D, U+8868, U+8870, U+8877, U+88DD, U+88FD, U+8907, U+896A, U+897F, U+898B, U+8996, U+89BD, U+89C0, U+89E3, U+89F8, U+8A00, U+8A02, U+8A0E, U+8A13, U+8A17, U+8A2A, U+8A2D, U+8A31, U+8A3A-8A3B, U+8A62, U+8A71, U+8A73, U+8A8C, U+8A9E, U+8AA4, U+8AB2, U+8ABF, U+8AEE, U+8AFE, U+8B02, U+8B39, U+8B6F, U+8B77, U+8B7D, U+8B8A, U+8C61, U+8CA0-8CA2, U+8CA9, U+8CB4, U+8CB7-8CB8, U+8CBC, U+8CC3, U+8CE0, U+8CEA, U+8CF4, U+8CFA, U+8CFC, U+8D0F, U+8D74, U+8D81, U+8D85, U+8D8A, U+8D9F, U+8DA8, U+8DB3, U+8DDD, U+8DE8, U+8DF3, U+8E0F, U+8E29, U+8E64, U+8ECC, U+8EF8, U+8F03, U+8F09, U+8F14-8F15, U+8F2A, U+8F2F, U+8F38, U+8F49, U+8F5F, U+8FA8, U+8FAF, U+8FB2, U+8FC5, U+8FCE, U+8FEA-8FEB, U+8FF0, U+8FF7, U+8FFD, U+9001, U+900F-9010, U+9014, U+901F-9020, U+9023, U+9031, U+903C, U+903E, U+904D, U+9054-9055, U+905C, U+9060, U+906D, U+9072, U+9077, U+907F-9080, U+908A, U+908F, U+90F5, U+9109, U+9165, U+916C, U+9192, U+91CD, U+91CF-91D1, U+91DD, U+9280, U+929C, U+92EA, U+932F, U+9375, U+9396, U+93C8, U+9580, U+9589, U+95B1, U+95C6, U+9644, U+964C, U+9650, U+9661-9664, U+966A, U+9673, U+9678, U+96A8, U+96AA, U+96C4-96C5, U+96D6, U+96D9, U+96DC, U+96E2-96E3, U+96F2, U+96F7, U+96FB, U+9727, U+975E, U+9760, U+9762, U+978B, U+97CC, U+97D3, U+97F3, U+97FF, U+9802, U+9805, U+9808, U+9818, U+982D, U+9838, U+9846, U+9867, U+986F, U+98A8, U+98DF, U+98F2, U+98FE, U+9905, U+9910, U+994B, U+99D0, U+9A45, U+9A57, U+9A5F, U+9BAE, U+9CF3, U+9EA5, U+9ED1, U+9F13, U+9F90, U+FF01, U+FF03-FF06, U+FF08-FF0B, U+FF0D-FF0F, U+FF1D, U+FF20, U+FF3C, U+FF5C, U+FF5E" }],
});

const DEFAULT_TITLE = "鹿飛 LUFÉ — 貨到了之後，我們接著走｜台灣品牌進菲律賓";
const DEFAULT_DESCRIPTION = "貨代把貨送到，故事才開始。鹿飛陪台灣品牌走完在菲律賓的第一年：市場探查、寄賣、公司落地、海外客服，四個方案各有價，先花 1～2 萬看市場反應。創辦人來自躍馬企業，底下是 42 年的國際物流。";
const DEFAULT_KEYWORDS = "台灣企業出海,菲律賓落地,菲律賓市場探查,菲律賓寄賣,菲律賓公司落地,海外客服外包,菲律賓 call center,出海起手包,連鎖餐飲出海,美妝出海菲律賓,北美通路,Costco 上架,鹿飛,LUFÉ";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: DEFAULT_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: DEFAULT_DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME }],
  keywords: DEFAULT_KEYWORDS,
  openGraph: {
    type: "website",
    locale: SITE_LOCALE,
    siteName: SITE_NAME,
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — 企業出海的導航系統`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: ["/og-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "32x32" },
    ],
    apple: "/apple-icon.png",
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b1a33" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-Hant"
      className={`${playfair.variable} ${inter.variable} ${notoSansTCCritical.variable} ${notoSansTC.variable}`}
    >
      <body>
        <MessageBoxProvider>
          <SiteStructuredData />
          <Navbar>
            <main id="main-content">{children}</main>
          </Navbar>
          <Footer />
          <MessageBox />
        </MessageBoxProvider>
      </body>
    </html>
  );
}
