import { CTA_LINE_EN } from "@/data/cta";
import { CASES, type CaseCardMeta, type CaseStudy } from "@/data/cases";

// Fingerprint of the Chinese case copy and data this English was translated from; registry.test.ts prints the value after the first run.
export const CASES_SOURCE_FINGERPRINT = "9136fed7a9cdd4dd";

const [goatMilkSoap, fishFloss, bubbleTea] = CASES;

const goatMilkSoapEn: CaseStudy = {
  ...goatMilkSoap,
  tags: [{ label: "Personal care", variant: "sky" }, { label: "North America", variant: "gold" }],
  num: "North America", title: "How can North American buyers understand a Taiwanese goat-milk soap?", titleBreakAfter: "a Taiwanese goat-milk soap",
  summary: "The product is not the problem. North American buyers do not understand it. The formula stays the same; the wording and labeling change before it enters North American mass retail.",
  stats: [{ label: "Now in North American mass retail", value: "North America" }, { label: "The wording and labeling change, not the product", value: "Formula unchanged" }, { label: "Claims and package labels reorganized under U.S. rules", value: "Compliant labeling" }],
  story: [
    { heading: "A soap that sells well in Taiwan was not understood in North America", paragraphs: ["This Taiwanese goat-milk soap brand has its own customers in Taiwan. When it wanted to enter North America, buyers could not see how it differed from other soaps on the shelf.", "The problem was not the product but how it was introduced. Selling points familiar to Taiwanese customers do not necessarily work in North America, and package information is not always what local buyers look for."], image: { src: "/images/cases/story/goat-soap-1-1600.webp", alt: "Handmade goat-milk soap on a wooden table", position: "center 75%" } },
    { heading: "First ask two questions: how do North American buyers see goat-milk soap, and who regulates it in the United States?", paragraphs: ["The first is a market question: what stories and claims do soaps in the same price range use, and is “handmade in Taiwan” a reason to pause at a North American shelf?", "The second is a rules question. The same soap can fall into different categories in the United States depending on its claims. True soap that only claims cleansing and soap that stresses moisturizing effects are overseen by different bodies; treatment claims take a different path. When the wording changes, the route changes with it. Every claim the brand wants to make must first be checked against this framework."], link: { text: "See how North America Retail works →", href: "/services/north-america" } },
    { heading: "The product's core stays the same; the wording and labeling change", paragraphs: ["The formula did not change. What changed was how people understood it: claims stayed within allowed limits, describing gentleness and ingredients rather than treatment; package information was rearranged around what North American buyers look for when they pick it up.", "The North American team handles local research, review, and negotiation; we are the brand's point of contact in Taiwan, so there is one person to contact."], image: { src: "/images/cases/story/goat-soap-2-1600.webp", alt: "Packaged handmade soap with kraft-paper labels" } },
    { heading: "Now the soap is in North American mass retail", paragraphs: ["From a counter in Taiwan to a shelf in North America, the formula is the same; the wording changed.", "Not every product should take this route. Sometimes we suggest waiting; that is also an answer."] },
  ],
  challenge: "The product is not the problem. North American buyers do not understand it.", approach: "The formula stays the same; the wording and labeling change.", result: "The soap entered North American mass retail.",
  timeline: [{ when: "Step one", title: "Market research", desc: "How North American buyers see goat-milk soap and what stories and claims soaps at the same price use" }, { when: "Step two", title: "Regulatory review", desc: "Which category the soap is in within the United States, what it can say, and what labels must say" }, { when: "Step three", title: "Wording and labeling", desc: "Claims and package labels reorganized under U.S. rules" }, { when: "Step four", title: "Enter the channel", desc: "Review and negotiation to enter North American mass retail" }],
  timelineHeading: ["This case took", "four steps"], cta: { heading: ["Your product may be stuck at", "“people do not understand it”"], body: CTA_LINE_EN },
};

const fishFlossEn: CaseStudy = {
  ...fishFloss,
  tags: [{ label: "Food", variant: "sky" }, { label: "United States", variant: "gold" }],
  title: "A Taiwanese fish-floss brand wants to enter the United States. What is the first hurdle?", summary: "It first looked like a marketing problem. The review showed that regulations and ingredients came first. We clarify FDA rules and ingredient adjustments before deciding how to introduce and package the product in the United States.", metaDescription: "The review showed that regulations and ingredients come first: FDA rules, ingredient adjustments, product introduction, and packaging for a Taiwanese fish-floss brand entering the United States.", statsLabel: "Delivered", cardSummary: "Clarify FDA rules plus required ingredient and label adjustments before packaging and launch.",
  stats: [{ label: "Confirm the regulator, seafood HACCP, and import requirements", value: "FDA" }, { label: "Review every ingredient for meat inputs, allergens, and color adjustments", value: "Formula" }, { label: "Replan packaging under U.S. labeling format", value: "Packaging" }],
  story: fishFloss.story.map((chapter, index) => ({ ...chapter, heading: ["Fish floss familiar in Taiwan is an unfamiliar food in the United States", "The research showed that regulations are the first hurdle", "U.S. consumers should decide how the product is introduced", "Replan packaging around how people read in the United States", "Prepare the route before discussing launch"][index]!, paragraphs: chapter.paragraphs.map((_, paragraphIndex) => [
    ["This Taiwanese fish-floss brand has a stable customer base at home and wanted to bring fish floss into the U.S. market. Its original plan was direct: find channels, market it, and list it.", "For U.S. consumers, fish floss is an unfamiliar product: they do not know what it is, how to eat it, or what it goes with. An earlier question surfaced: can this product be legally imported?"],
    ["We started with a regulatory review. In the United States, fish floss made only from fish is regulated by the FDA as a seafood product: overseas processors must meet seafood HACCP requirements, importers must verify this, facilities must complete food-facility registration, and every shipment needs prior notice. Whether dried fish floss must follow low-acid canned-food procedures depends on measured water activity, not guesswork.", "Problems in common Taiwanese fish-floss formulas often sit in the ingredient list. If a formula includes enough meat floss, it comes under the U.S. Department of Agriculture, while eligibility for Taiwanese meat products is tightly restricted; pork-derived ingredients such as lard also face animal-disease import restrictions.", "Soy sauce brings soy and wheat, batter brings wheat, and sesame brings sesame—each is a major allergen that U.S. rules require to be labeled. Fish is one too, and the species must be named. Colors and preservatives must be allowed in the United States. We lay out the ingredient list and check each item to separate formula changes from label changes."],
    ["Once the regulatory path is clear, the next question is whether U.S. consumers know what this product is and how to eat it.", "The name is the first hurdle. “Fish Floss” is unfamiliar to most U.S. consumers, while “flakes” can suggest fish food. A more useful reference is a savory topping they already know: fish floss can go on rice, eggs, and salad, rather than being only a traditional food for porridge. The clearest name and explanation must be tried with real U.S. consumers, not guessed in Taiwan.", "That puts two routes on the table: Asian supermarkets, where buyers already know fish floss and price competes with established imports; or mainstream channels, where the product needs a new name and eating instructions but has no direct competitor. Our job is to help the brand choose with evidence, not choose for it."],
    ["U.S. food labels have a fixed format: the name must make clear what the product is and identify the fish species; net weight uses both metric and U.S. units; serving size follows U.S. rules; ingredients are ordered by amount; allergens are clearly listed; and country of origin is shown.", "Packaging also needs to fit different use and climate. A small, resealable pack makes more sense than a large Taiwanese jar for a product people are trying for the first time and that is sensitive to moisture. An English product name with a descriptive explanation—such as shredded fish with the species named—plus one sentence on how to eat it lets people understand it at first glance."],
    ["The first deliverable was not a listing number but a clear U.S. entry path: ingredients to change, items that only need relabeling, documents to prepare, packaging changes, and product wording—organized enough to discuss directly with importers and channels.", "For food brands entering the United States, doing this work first keeps later steps from being repeated. The brand is now using this route to talk with mainstream U.S. channels.", "If the review shows that the formula would need major changes to enter, we say so. Sometimes we suggest waiting; that is also an answer."],
  ][index]![paragraphIndex]!), image: chapter.image ? { ...chapter.image, alt: ["Dried fish and shrimp at a market stall", "", "", "Unprinted food-packaging bags", ""][index]! } : undefined, link: chapter.link ? { ...chapter.link, text: "North America takes a different route. See how North America Retail works →" } : undefined })),
  challenge: "The brand planned to find channels and market directly, but legal U.S. import eligibility, ingredients, and labels had not been checked, and U.S. consumers did not know the product.", approach: "Review FDA and import rules and every ingredient, then use U.S. consumer tastings and naming tests to decide the introduction and plan packaging under U.S. labeling format.", result: "A U.S. entry path ready for importer and channel discussions: ingredient changes, documents, packaging, and product wording.",
  timeline: [{ when: "Step one", title: "Regulatory review", desc: "Confirm the regulator, seafood HACCP, facility registration, prior notice, and water activity" }, { when: "Step two", title: "Ingredient review", desc: "Check meat inputs, lard, allergens, colors, and preservatives one by one" }, { when: "Step three", title: "Consumer testing", desc: "Use blind tastings and naming tests to see how U.S. consumers understand and eat it" }, { when: "Step four", title: "Packaging plan", desc: "Plan the name, nutrition facts, allergens, and small packs under U.S. labeling format" }],
  timelineHeading: ["This case has", "four steps"], cta: { heading: ["Your product may be stuck at", "the same hurdle"], body: CTA_LINE_EN, secondary: "Not sure which case is closest? Start with the 2-minute Situation Check" },
};

const bubbleTeaEn: CaseStudy = {
  ...bubbleTea,
  tags: [{ label: "Beverages", variant: "sky" }, { label: "Southeast Asia", variant: "gold" }], num: "More than ten", title: "How did a bubble-tea brand grow from zero to more than ten stores in the Philippines?", summary: "A bubble-tea brand built from zero by our local Philippine partners: starting with Taiwanese tea, adapting local taste and pricing, validating the first store, then opening franchising—now with more than ten stores.",
  stats: [{ label: "From the first store to more than ten stores", value: "More than ten" }, { label: "Franchising opened only after the first store was stable", value: "Franchising" }, { label: "Ingredients imported from Taiwan; flavors and prices adapted locally", value: "Taiwanese tea" }],
  story: [
    { heading: "This is not a case we did for someone else; our partners built it themselves", paragraphs: ["This bubble-tea brand was built from zero by our local Philippine partners. They first built an English-language education organization—recruiting teachers, finding space, and enrolling their first student—then built this bubble-tea chain from zero.", "We include it because these are the people beside Taiwanese brands when they set up in the Philippines: they have opened their first store, hired their first team, and decided for themselves when franchising should open."], image: { src: "/images/cases/story/bubble-tea-1-1600.webp", alt: "Bubble tea at a counter" } },
    { heading: "International brands were already in the market", paragraphs: ["When it entered, international brands were already in the local bubble-tea market. A new brand did not need to be bigger than them; it needed to find its own position and protect its formula."] },
    { heading: "Start with Taiwanese tea, then adapt local taste and pricing", paragraphs: ["Taiwanese tea is the base, and ingredients are imported from Taiwan. But flavors and pricing were adjusted for local habits—what sells in Taiwan is not necessarily what people in the Philippines will pay for."], image: { src: "/images/cases/story/bubble-tea-tasting-1600.webp", alt: "Three bubble teas with different flavors", position: "center 62%", aspect: "16/9" } },
    { heading: "Validate one store before opening franchising", paragraphs: ["It did not roll out stores immediately. It opened one store first, confirmed that taste, pricing, and operations worked, then expanded through franchising. The brand now has more than ten stores in the Philippines.", "We take Taiwanese brands to the Philippines in the same order: first ask local consumers through a Market Test, then list small volumes through Consignment; after that is stable, discuss Company Setup."], showStageLinks: true },
  ],
  challenge: "International brands were already in the local bubble-tea market. A new brand needed to find its position and protect its formula.", approach: "Start with Taiwanese tea and imported ingredients, adjust flavor and price locally, validate the first store, then open franchising.", result: "Built from zero, the brand now has more than ten stores in the Philippines and franchising is open.", cta: { body: CTA_LINE_EN, secondary: "Still unsure? Start with the 2-minute Situation Check" },
};

export const CASES_EN: readonly CaseStudy[] = [goatMilkSoapEn, fishFlossEn, bubbleTeaEn];
export const CASE_CARD_META_EN: Record<string, CaseCardMeta> = {
  "goat-milk-soap-global": { headline: "The formula stays the same; the wording and labeling change", painTitle: "A soap that sells well in Taiwan was not understood in North America", beats: ["A Taiwanese goat-milk soap brand with its own customers in Taiwan wants to enter North America", "North American buyers pick it up but cannot see how it differs from other soaps", "Claims stay within allowed limits and package information is rearranged around what buyers seek", "The soap entered North American mass retail"] },
  "fish-floss-us-fda": { headline: "Clear regulations before packaging and launch", painTitle: "It looked like a marketing problem, but regulations and ingredients came first", beats: ["A Taiwanese fish-floss brand planned to find channels and market directly in the United States", "Research showed the product had to clear FDA requirements first, including ingredients, allergens, and color labels", "Review every regulation and ingredient, then use U.S. tastings and naming tests to decide the introduction", "Prepare an entry path for importer discussions and replan packaging under U.S. labeling format"] },
  "bubble-tea": { headline: "Validate one store before opening franchising", painTitle: "What sells in Taiwan is not necessarily what people in the Philippines will pay for", beats: ["Our local Philippine partners built an English-language education organization, then a bubble-tea brand from zero", "International brands were already there, so the new brand needed its position and formula", "Taiwanese tea and imported ingredients stayed, while flavor and price changed locally; one store was validated first", "Franchising opened only after the first store was stable; the brand now has more than ten stores"] },
};
export const INDUSTRIES_EN = [{ value: "all", label: "All industries" }, { value: "food", label: "Food" }, { value: "personal-care", label: "Personal care" }, { value: "fnb", label: "Food and beverages" }] as const;
export const MARKETS_EN = [{ value: "all", label: "All markets" }, { value: "north-america", label: "North America" }, { value: "sea", label: "Southeast Asia" }] as const;
export const getCaseEn = (slug: string) => CASES_EN.find((caseItem) => caseItem.slug === slug);
